@ECHO OFF

SET APP_NAME=%1

SET TOMCAT_VERSION=10.1.10

IF EXIST "D:\prj\apache-tomcat-%TOMCAT_VERSION%\" (
  SET TOMCAT_FOLDER=D:\prj\apache-tomcat-%TOMCAT_VERSION%
) ELSE (
  IF EXIST "%USERPROFILE%\prj\apache-tomcat-%TOMCAT_VERSION%" (
    SET TOMCAT_FOLDER=%USERPROFILE%\prj\apache-tomcat-%TOMCAT_VERSION%
  ) ELSE (
    ECHO TOMCAT FOLDER FOR VERSION %TOMCAT_VERSION% NOT FOUND
    EXIT 1
  )
)

ECHO TOMCAT FOLDER: %TOMCAT_FOLDER%

CALL buildprod.bat
RMDIR /S /Q %TOMCAT_FOLDER%\work\Catalina\localhost\%APP_NAME%\
RMDIR /S /Q %TOMCAT_FOLDER%\webapps\%APP_NAME%\
XCOPY dist\%APP_NAME%\*.* %TOMCAT_FOLDER%\webapps\%APP_NAME%\ /S
